left_front_wheel_joint_controller:
  simple_chassis_controller:
    type: simple_chassis_controller/SimpleChassisController
    joint:left_front_wheel_joint
     pid: {p: 100.0, i: 0.01, d: 10.0}  


     left_front_wheel_joint_controller:
  simple_chassis_controller:
    type: simple_chassis_controller/SimpleChassisController
    joint:left_front_wheel_joint
     pid: {p: 100.0, i: 0.01, d: 10.0}


     left_front_wheel_joint_controller:
  simple_chassis_controller:
    type: simple_chassis_controller/SimpleChassisController
    joint:left_front_wheel_joint
     pid: {p: 100.0, i: 0.01, d: 10.0}

     
     left_front_wheel_joint_controller:
  simple_chassis_controller:
    type: simple_chassis_controller/SimpleChassisController
    joint:left_front_wheel_joint
     pid: {p: 100.0, i: 0.01, d: 10.0}
# joint1_position_controller:{prefix}_wheel_joint
#     type: effort_controllers/JointPositionController
#     joint: joint1
#     pid: {p: 100.0, i: 0.01, d: 10.0}
#   joint2_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint2
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50