// Generated by gencpp from file rm_msgs/CameraStatus.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CAMERASTATUS_H
#define RM_MSGS_MESSAGE_CAMERASTATUS_H

#include <ros/service_traits.h>


#include <rm_msgs/CameraStatusRequest.h>
#include <rm_msgs/CameraStatusResponse.h>


namespace rm_msgs
{

struct CameraStatus
{

typedef CameraStatusRequest Request;
typedef CameraStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraStatus
} // namespace rm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rm_msgs::CameraStatus > {
  static const char* value()
  {
    return "86773025f35634422f96dc69ae7b5cfe";
  }

  static const char* value(const ::rm_msgs::CameraStatus&) { return value(); }
};

template<>
struct DataType< ::rm_msgs::CameraStatus > {
  static const char* value()
  {
    return "rm_msgs/CameraStatus";
  }

  static const char* value(const ::rm_msgs::CameraStatus&) { return value(); }
};


// service_traits::MD5Sum< ::rm_msgs::CameraStatusRequest> should match
// service_traits::MD5Sum< ::rm_msgs::CameraStatus >
template<>
struct MD5Sum< ::rm_msgs::CameraStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::CameraStatus >::value();
  }
  static const char* value(const ::rm_msgs::CameraStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::CameraStatusRequest> should match
// service_traits::DataType< ::rm_msgs::CameraStatus >
template<>
struct DataType< ::rm_msgs::CameraStatusRequest>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::CameraStatus >::value();
  }
  static const char* value(const ::rm_msgs::CameraStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rm_msgs::CameraStatusResponse> should match
// service_traits::MD5Sum< ::rm_msgs::CameraStatus >
template<>
struct MD5Sum< ::rm_msgs::CameraStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::CameraStatus >::value();
  }
  static const char* value(const ::rm_msgs::CameraStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::CameraStatusResponse> should match
// service_traits::DataType< ::rm_msgs::CameraStatus >
template<>
struct DataType< ::rm_msgs::CameraStatusResponse>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::CameraStatus >::value();
  }
  static const char* value(const ::rm_msgs::CameraStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RM_MSGS_MESSAGE_CAMERASTATUS_H
