// Generated by gencpp from file rm_msgs/EnableImuTrigger.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ENABLEIMUTRIGGER_H
#define RM_MSGS_MESSAGE_ENABLEIMUTRIGGER_H

#include <ros/service_traits.h>


#include <rm_msgs/EnableImuTriggerRequest.h>
#include <rm_msgs/EnableImuTriggerResponse.h>


namespace rm_msgs
{

struct EnableImuTrigger
{

typedef EnableImuTriggerRequest Request;
typedef EnableImuTriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableImuTrigger
} // namespace rm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rm_msgs::EnableImuTrigger > {
  static const char* value()
  {
    return "1e2c36312701f0610562a77ad6902d8f";
  }

  static const char* value(const ::rm_msgs::EnableImuTrigger&) { return value(); }
};

template<>
struct DataType< ::rm_msgs::EnableImuTrigger > {
  static const char* value()
  {
    return "rm_msgs/EnableImuTrigger";
  }

  static const char* value(const ::rm_msgs::EnableImuTrigger&) { return value(); }
};


// service_traits::MD5Sum< ::rm_msgs::EnableImuTriggerRequest> should match
// service_traits::MD5Sum< ::rm_msgs::EnableImuTrigger >
template<>
struct MD5Sum< ::rm_msgs::EnableImuTriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::EnableImuTrigger >::value();
  }
  static const char* value(const ::rm_msgs::EnableImuTriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::EnableImuTriggerRequest> should match
// service_traits::DataType< ::rm_msgs::EnableImuTrigger >
template<>
struct DataType< ::rm_msgs::EnableImuTriggerRequest>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::EnableImuTrigger >::value();
  }
  static const char* value(const ::rm_msgs::EnableImuTriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rm_msgs::EnableImuTriggerResponse> should match
// service_traits::MD5Sum< ::rm_msgs::EnableImuTrigger >
template<>
struct MD5Sum< ::rm_msgs::EnableImuTriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::EnableImuTrigger >::value();
  }
  static const char* value(const ::rm_msgs::EnableImuTriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::EnableImuTriggerResponse> should match
// service_traits::DataType< ::rm_msgs::EnableImuTrigger >
template<>
struct DataType< ::rm_msgs::EnableImuTriggerResponse>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::EnableImuTrigger >::value();
  }
  static const char* value(const ::rm_msgs::EnableImuTriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RM_MSGS_MESSAGE_ENABLEIMUTRIGGER_H
