// Generated by gencpp from file rm_msgs/EnableImuTriggerResponse.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ENABLEIMUTRIGGERRESPONSE_H
#define RM_MSGS_MESSAGE_ENABLEIMUTRIGGERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct EnableImuTriggerResponse_
{
  typedef EnableImuTriggerResponse_<ContainerAllocator> Type;

  EnableImuTriggerResponse_()
    : is_success(false)  {
    }
  EnableImuTriggerResponse_(const ContainerAllocator& _alloc)
    : is_success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_success_type;
  _is_success_type is_success;





  typedef boost::shared_ptr< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EnableImuTriggerResponse_

typedef ::rm_msgs::EnableImuTriggerResponse_<std::allocator<void> > EnableImuTriggerResponse;

typedef boost::shared_ptr< ::rm_msgs::EnableImuTriggerResponse > EnableImuTriggerResponsePtr;
typedef boost::shared_ptr< ::rm_msgs::EnableImuTriggerResponse const> EnableImuTriggerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator1> & lhs, const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_success == rhs.is_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator1> & lhs, const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa3e942e5cfe76a6a46f20a0780b2cf3";
  }

  static const char* value(const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa3e942e5cfe76a6ULL;
  static const uint64_t static_value2 = 0xa46f20a0780b2cf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/EnableImuTriggerResponse";
  }

  static const char* value(const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_success\n"
"\n"
;
  }

  static const char* value(const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableImuTriggerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::EnableImuTriggerResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ENABLEIMUTRIGGERRESPONSE_H
