// Generated by gencpp from file rm_msgs/KalmanData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_KALMANDATA_H
#define RM_MSGS_MESSAGE_KALMANDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct KalmanData_
{
  typedef KalmanData_<ContainerAllocator> Type;

  KalmanData_()
    : header()
    , real_detection_pose()
    , filtered_detection_pose()
    , real_detection_twist()
    , filtered_detection_twist()  {
    }
  KalmanData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , real_detection_pose(_alloc)
    , filtered_detection_pose(_alloc)
    , real_detection_twist(_alloc)
    , filtered_detection_twist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _real_detection_pose_type;
  _real_detection_pose_type real_detection_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _filtered_detection_pose_type;
  _filtered_detection_pose_type filtered_detection_pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _real_detection_twist_type;
  _real_detection_twist_type real_detection_twist;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _filtered_detection_twist_type;
  _filtered_detection_twist_type filtered_detection_twist;





  typedef boost::shared_ptr< ::rm_msgs::KalmanData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::KalmanData_<ContainerAllocator> const> ConstPtr;

}; // struct KalmanData_

typedef ::rm_msgs::KalmanData_<std::allocator<void> > KalmanData;

typedef boost::shared_ptr< ::rm_msgs::KalmanData > KalmanDataPtr;
typedef boost::shared_ptr< ::rm_msgs::KalmanData const> KalmanDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::KalmanData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::KalmanData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::KalmanData_<ContainerAllocator1> & lhs, const ::rm_msgs::KalmanData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.real_detection_pose == rhs.real_detection_pose &&
    lhs.filtered_detection_pose == rhs.filtered_detection_pose &&
    lhs.real_detection_twist == rhs.real_detection_twist &&
    lhs.filtered_detection_twist == rhs.filtered_detection_twist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::KalmanData_<ContainerAllocator1> & lhs, const ::rm_msgs::KalmanData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::KalmanData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::KalmanData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::KalmanData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::KalmanData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::KalmanData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::KalmanData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::KalmanData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "076b9f9dc5aab232f694a2e05a2a0a8c";
  }

  static const char* value(const ::rm_msgs::KalmanData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x076b9f9dc5aab232ULL;
  static const uint64_t static_value2 = 0xf694a2e05a2a0a8cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::KalmanData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/KalmanData";
  }

  static const char* value(const ::rm_msgs::KalmanData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::KalmanData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Pose real_detection_pose\n"
"geometry_msgs/Pose filtered_detection_pose\n"
"geometry_msgs/Twist real_detection_twist\n"
"geometry_msgs/Twist filtered_detection_twist\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rm_msgs::KalmanData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::KalmanData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.real_detection_pose);
      stream.next(m.filtered_detection_pose);
      stream.next(m.real_detection_twist);
      stream.next(m.filtered_detection_twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KalmanData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::KalmanData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::KalmanData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "real_detection_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.real_detection_pose);
    s << indent << "filtered_detection_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.filtered_detection_pose);
    s << indent << "real_detection_twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.real_detection_twist);
    s << indent << "filtered_detection_twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.filtered_detection_twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_KALMANDATA_H
