// Generated by gencpp from file rm_msgs/PowerHeatData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_POWERHEATDATA_H
#define RM_MSGS_MESSAGE_POWERHEATDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct PowerHeatData_
{
  typedef PowerHeatData_<ContainerAllocator> Type;

  PowerHeatData_()
    : chassis_volt(0.0)
    , chassis_current(0.0)
    , chassis_power(0.0)
    , chassis_power_buffer(0)
    , shooter_id_1_17_mm_cooling_heat(0)
    , shooter_id_2_17_mm_cooling_heat(0)
    , shooter_id_1_42_mm_cooling_heat(0)
    , stamp()  {
    }
  PowerHeatData_(const ContainerAllocator& _alloc)
    : chassis_volt(0.0)
    , chassis_current(0.0)
    , chassis_power(0.0)
    , chassis_power_buffer(0)
    , shooter_id_1_17_mm_cooling_heat(0)
    , shooter_id_2_17_mm_cooling_heat(0)
    , shooter_id_1_42_mm_cooling_heat(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef float _chassis_volt_type;
  _chassis_volt_type chassis_volt;

   typedef float _chassis_current_type;
  _chassis_current_type chassis_current;

   typedef float _chassis_power_type;
  _chassis_power_type chassis_power;

   typedef uint16_t _chassis_power_buffer_type;
  _chassis_power_buffer_type chassis_power_buffer;

   typedef uint16_t _shooter_id_1_17_mm_cooling_heat_type;
  _shooter_id_1_17_mm_cooling_heat_type shooter_id_1_17_mm_cooling_heat;

   typedef uint16_t _shooter_id_2_17_mm_cooling_heat_type;
  _shooter_id_2_17_mm_cooling_heat_type shooter_id_2_17_mm_cooling_heat;

   typedef uint16_t _shooter_id_1_42_mm_cooling_heat_type;
  _shooter_id_1_42_mm_cooling_heat_type shooter_id_1_42_mm_cooling_heat;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::PowerHeatData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::PowerHeatData_<ContainerAllocator> const> ConstPtr;

}; // struct PowerHeatData_

typedef ::rm_msgs::PowerHeatData_<std::allocator<void> > PowerHeatData;

typedef boost::shared_ptr< ::rm_msgs::PowerHeatData > PowerHeatDataPtr;
typedef boost::shared_ptr< ::rm_msgs::PowerHeatData const> PowerHeatDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::PowerHeatData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::PowerHeatData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::PowerHeatData_<ContainerAllocator1> & lhs, const ::rm_msgs::PowerHeatData_<ContainerAllocator2> & rhs)
{
  return lhs.chassis_volt == rhs.chassis_volt &&
    lhs.chassis_current == rhs.chassis_current &&
    lhs.chassis_power == rhs.chassis_power &&
    lhs.chassis_power_buffer == rhs.chassis_power_buffer &&
    lhs.shooter_id_1_17_mm_cooling_heat == rhs.shooter_id_1_17_mm_cooling_heat &&
    lhs.shooter_id_2_17_mm_cooling_heat == rhs.shooter_id_2_17_mm_cooling_heat &&
    lhs.shooter_id_1_42_mm_cooling_heat == rhs.shooter_id_1_42_mm_cooling_heat &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::PowerHeatData_<ContainerAllocator1> & lhs, const ::rm_msgs::PowerHeatData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PowerHeatData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PowerHeatData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PowerHeatData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e95858fa10d84e626e18f0e745f78532";
  }

  static const char* value(const ::rm_msgs::PowerHeatData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe95858fa10d84e62ULL;
  static const uint64_t static_value2 = 0x6e18f0e745f78532ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/PowerHeatData";
  }

  static const char* value(const ::rm_msgs::PowerHeatData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 chassis_volt\n"
"float32 chassis_current\n"
"float32 chassis_power\n"
"uint16 chassis_power_buffer\n"
"uint16 shooter_id_1_17_mm_cooling_heat\n"
"uint16 shooter_id_2_17_mm_cooling_heat\n"
"uint16 shooter_id_1_42_mm_cooling_heat\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::PowerHeatData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_volt);
      stream.next(m.chassis_current);
      stream.next(m.chassis_power);
      stream.next(m.chassis_power_buffer);
      stream.next(m.shooter_id_1_17_mm_cooling_heat);
      stream.next(m.shooter_id_2_17_mm_cooling_heat);
      stream.next(m.shooter_id_1_42_mm_cooling_heat);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerHeatData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::PowerHeatData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::PowerHeatData_<ContainerAllocator>& v)
  {
    s << indent << "chassis_volt: ";
    Printer<float>::stream(s, indent + "  ", v.chassis_volt);
    s << indent << "chassis_current: ";
    Printer<float>::stream(s, indent + "  ", v.chassis_current);
    s << indent << "chassis_power: ";
    Printer<float>::stream(s, indent + "  ", v.chassis_power);
    s << indent << "chassis_power_buffer: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_power_buffer);
    s << indent << "shooter_id_1_17_mm_cooling_heat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shooter_id_1_17_mm_cooling_heat);
    s << indent << "shooter_id_2_17_mm_cooling_heat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shooter_id_2_17_mm_cooling_heat);
    s << indent << "shooter_id_1_42_mm_cooling_heat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shooter_id_1_42_mm_cooling_heat);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_POWERHEATDATA_H
