// Generated by gencpp from file rm_msgs/RobotHurt.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ROBOTHURT_H
#define RM_MSGS_MESSAGE_ROBOTHURT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RobotHurt_
{
  typedef RobotHurt_<ContainerAllocator> Type;

  RobotHurt_()
    : armor_id(0)
    , hurt_type(0)
    , stamp()  {
    }
  RobotHurt_(const ContainerAllocator& _alloc)
    : armor_id(0)
    , hurt_type(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _armor_id_type;
  _armor_id_type armor_id;

   typedef uint8_t _hurt_type_type;
  _hurt_type_type hurt_type;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::RobotHurt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RobotHurt_<ContainerAllocator> const> ConstPtr;

}; // struct RobotHurt_

typedef ::rm_msgs::RobotHurt_<std::allocator<void> > RobotHurt;

typedef boost::shared_ptr< ::rm_msgs::RobotHurt > RobotHurtPtr;
typedef boost::shared_ptr< ::rm_msgs::RobotHurt const> RobotHurtConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RobotHurt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RobotHurt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RobotHurt_<ContainerAllocator1> & lhs, const ::rm_msgs::RobotHurt_<ContainerAllocator2> & rhs)
{
  return lhs.armor_id == rhs.armor_id &&
    lhs.hurt_type == rhs.hurt_type &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RobotHurt_<ContainerAllocator1> & lhs, const ::rm_msgs::RobotHurt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RobotHurt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RobotHurt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RobotHurt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RobotHurt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RobotHurt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RobotHurt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RobotHurt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "603a676d8da8f575fe2daaa14c7ac198";
  }

  static const char* value(const ::rm_msgs::RobotHurt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x603a676d8da8f575ULL;
  static const uint64_t static_value2 = 0xfe2daaa14c7ac198ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RobotHurt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RobotHurt";
  }

  static const char* value(const ::rm_msgs::RobotHurt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RobotHurt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 armor_id\n"
"uint8 hurt_type\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::RobotHurt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RobotHurt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.armor_id);
      stream.next(m.hurt_type);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotHurt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RobotHurt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RobotHurt_<ContainerAllocator>& v)
  {
    s << indent << "armor_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.armor_id);
    s << indent << "hurt_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hurt_type);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ROBOTHURT_H
