// Generated by gencpp from file rm_msgs/StateCmd.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_STATECMD_H
#define RM_MSGS_MESSAGE_STATECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct StateCmd_
{
  typedef StateCmd_<ContainerAllocator> Type;

  StateCmd_()
    : mode(0)
    , data(0.0)
    , stamp()  {
    }
  StateCmd_(const ContainerAllocator& _alloc)
    : mode(0)
    , data(0.0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef double _data_type;
  _data_type data;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::StateCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::StateCmd_<ContainerAllocator> const> ConstPtr;

}; // struct StateCmd_

typedef ::rm_msgs::StateCmd_<std::allocator<void> > StateCmd;

typedef boost::shared_ptr< ::rm_msgs::StateCmd > StateCmdPtr;
typedef boost::shared_ptr< ::rm_msgs::StateCmd const> StateCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::StateCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::StateCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::StateCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::StateCmd_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.data == rhs.data &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::StateCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::StateCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::StateCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::StateCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::StateCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::StateCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::StateCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::StateCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::StateCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55348fd528431bf4c4b507668d894589";
  }

  static const char* value(const ::rm_msgs::StateCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55348fd528431bf4ULL;
  static const uint64_t static_value2 = 0xc4b507668d894589ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::StateCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/StateCmd";
  }

  static const char* value(const ::rm_msgs::StateCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::StateCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
"float64 data\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::StateCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::StateCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.data);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::StateCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::StateCmd_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_STATECMD_H
