// Generated by gencpp from file rm_msgs/StatusChangeResponse.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_STATUSCHANGERESPONSE_H
#define RM_MSGS_MESSAGE_STATUSCHANGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct StatusChangeResponse_
{
  typedef StatusChangeResponse_<ContainerAllocator> Type;

  StatusChangeResponse_()
    : switch_is_success(false)  {
    }
  StatusChangeResponse_(const ContainerAllocator& _alloc)
    : switch_is_success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _switch_is_success_type;
  _switch_is_success_type switch_is_success;





  typedef boost::shared_ptr< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StatusChangeResponse_

typedef ::rm_msgs::StatusChangeResponse_<std::allocator<void> > StatusChangeResponse;

typedef boost::shared_ptr< ::rm_msgs::StatusChangeResponse > StatusChangeResponsePtr;
typedef boost::shared_ptr< ::rm_msgs::StatusChangeResponse const> StatusChangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::StatusChangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::StatusChangeResponse_<ContainerAllocator1> & lhs, const ::rm_msgs::StatusChangeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.switch_is_success == rhs.switch_is_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::StatusChangeResponse_<ContainerAllocator1> & lhs, const ::rm_msgs::StatusChangeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b239f2cd0aa0d5816b7c3243eb924c4";
  }

  static const char* value(const ::rm_msgs::StatusChangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b239f2cd0aa0d58ULL;
  static const uint64_t static_value2 = 0x16b7c3243eb924c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/StatusChangeResponse";
  }

  static const char* value(const ::rm_msgs::StatusChangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool switch_is_success\n"
"\n"
;
  }

  static const char* value(const ::rm_msgs::StatusChangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.switch_is_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusChangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::StatusChangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::StatusChangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "switch_is_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch_is_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_STATUSCHANGERESPONSE_H
