(cl:defpackage rm_msgs-srv
  (:use )
  (:export
   "CAMERASTATUS"
   "<CAMERASTATUS-REQUEST>"
   "CAMERASTATUS-REQUEST"
   "<CAMERASTATUS-RESPONSE>"
   "CAMERASTATUS-RESPONSE"
   "CONTINOUSDETECTORSWITCH"
   "<CONTINOUSDETECTORSWITCH-REQUEST>"
   "CONTINOUSDETECTORSWITCH-REQUEST"
   "<CONTINOUSDETECTORSWITCH-RESPONSE>"
   "CONTINOUSDETECTORSWITCH-RESPONSE"
   "ENABLEIMUTRIGGER"
   "<ENABLEIMUTRIGGER-REQUEST>"
   "ENABLEIMUTRIGGER-REQUEST"
   "<ENABLEIMUTRIGGER-RESPONSE>"
   "ENABLEIMUTRIGGER-RESPONSE"
   "STATUSCHANGE"
   "<STATUSCHANGE-REQUEST>"
   "STATUSCHANGE-REQUEST"
   "<STATUSCHANGE-RESPONSE>"
   "STATUSCHANGE-RESPONSE"
  ))

