# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/BulletRemaining.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class BulletRemaining(genpy.Message):
  _md5sum = "43e123a32cc9ba99f4b185dfa52ac9e7"
  _type = "rm_msgs/BulletRemaining"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 bullet_remaining_num_17_mm
uint16 bullet_remaining_num_42_mm
uint16 coin_remaining_num

time stamp
"""
  __slots__ = ['bullet_remaining_num_17_mm','bullet_remaining_num_42_mm','coin_remaining_num','stamp']
  _slot_types = ['uint16','uint16','uint16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bullet_remaining_num_17_mm,bullet_remaining_num_42_mm,coin_remaining_num,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BulletRemaining, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bullet_remaining_num_17_mm is None:
        self.bullet_remaining_num_17_mm = 0
      if self.bullet_remaining_num_42_mm is None:
        self.bullet_remaining_num_42_mm = 0
      if self.coin_remaining_num is None:
        self.coin_remaining_num = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.bullet_remaining_num_17_mm = 0
      self.bullet_remaining_num_42_mm = 0
      self.coin_remaining_num = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3H2I().pack(_x.bullet_remaining_num_17_mm, _x.bullet_remaining_num_42_mm, _x.coin_remaining_num, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.bullet_remaining_num_17_mm, _x.bullet_remaining_num_42_mm, _x.coin_remaining_num, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3H2I().pack(_x.bullet_remaining_num_17_mm, _x.bullet_remaining_num_42_mm, _x.coin_remaining_num, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.bullet_remaining_num_17_mm, _x.bullet_remaining_num_42_mm, _x.coin_remaining_num, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3H2I = None
def _get_struct_3H2I():
    global _struct_3H2I
    if _struct_3H2I is None:
        _struct_3H2I = struct.Struct("<3H2I")
    return _struct_3H2I
