# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/EngineerCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class EngineerCmd(genpy.Message):
  _md5sum = "99c50feb8f06ee5ae16f37b16ca0b9f7"
  _type = "rm_msgs/EngineerCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string current_step_name
uint32 finished_step
uint32 total_steps

string step_queue_name
bool symbol
time stamp
"""
  __slots__ = ['current_step_name','finished_step','total_steps','step_queue_name','symbol','stamp']
  _slot_types = ['string','uint32','uint32','string','bool','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       current_step_name,finished_step,total_steps,step_queue_name,symbol,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EngineerCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.current_step_name is None:
        self.current_step_name = ''
      if self.finished_step is None:
        self.finished_step = 0
      if self.total_steps is None:
        self.total_steps = 0
      if self.step_queue_name is None:
        self.step_queue_name = ''
      if self.symbol is None:
        self.symbol = False
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.current_step_name = ''
      self.finished_step = 0
      self.total_steps = 0
      self.step_queue_name = ''
      self.symbol = False
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.current_step_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.finished_step, _x.total_steps))
      _x = self.step_queue_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.symbol, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_step_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_step_name = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.finished_step, _x.total_steps,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.step_queue_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.step_queue_name = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.symbol, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_B2I().unpack(str[start:end])
      self.symbol = bool(self.symbol)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.current_step_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.finished_step, _x.total_steps))
      _x = self.step_queue_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.symbol, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_step_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_step_name = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.finished_step, _x.total_steps,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.step_queue_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.step_queue_name = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.symbol, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_B2I().unpack(str[start:end])
      self.symbol = bool(self.symbol)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
