# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/GameStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class GameStatus(genpy.Message):
  _md5sum = "4a9e39abf3567cbe229e978307d8a9be"
  _type = "rm_msgs/GameStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 game_type
uint8 game_progress
uint16 stage_remain_time
uint64 sync_time_stamp

time stamp
"""
  __slots__ = ['game_type','game_progress','stage_remain_time','sync_time_stamp','stamp']
  _slot_types = ['uint8','uint8','uint16','uint64','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       game_type,game_progress,stage_remain_time,sync_time_stamp,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GameStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.game_type is None:
        self.game_type = 0
      if self.game_progress is None:
        self.game_progress = 0
      if self.stage_remain_time is None:
        self.stage_remain_time = 0
      if self.sync_time_stamp is None:
        self.sync_time_stamp = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.game_type = 0
      self.game_progress = 0
      self.stage_remain_time = 0
      self.sync_time_stamp = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2BHQ2I().pack(_x.game_type, _x.game_progress, _x.stage_remain_time, _x.sync_time_stamp, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.game_type, _x.game_progress, _x.stage_remain_time, _x.sync_time_stamp, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2BHQ2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2BHQ2I().pack(_x.game_type, _x.game_progress, _x.stage_remain_time, _x.sync_time_stamp, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.game_type, _x.game_progress, _x.stage_remain_time, _x.sync_time_stamp, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2BHQ2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BHQ2I = None
def _get_struct_2BHQ2I():
    global _struct_2BHQ2I
    if _struct_2BHQ2I is None:
        _struct_2BHQ2I = struct.Struct("<2BHQ2I")
    return _struct_2BHQ2I
