# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/IcraBuffDebuffZoneStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class IcraBuffDebuffZoneStatus(genpy.Message):
  _md5sum = "2f6fc310c2ebda62f2d87ce47e0d1eb0"
  _type = "rm_msgs/IcraBuffDebuffZoneStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 f_1_zone_status
uint8 f_1_zone_buff_debuff_status
uint8 f_2_zone_status
uint8 f_2_zone_buff_debuff_status
uint8 f_3_zone_status
uint8 f_3_zone_buff_debuff_status
uint8 f_4_zone_status
uint8 f_4_zone_buff_debuff_status
uint8 f_5_zone_status
uint8 f_5_zone_buff_debuff_status
uint8 f_6_zone_status
uint8 f_6_zone_buff_debuff_status
uint16 red_1_bullet_left
uint16 red_2_bullet_left
uint16 blue_1_bullet_left
uint16 blue_2_bullet_left

time stamp
"""
  __slots__ = ['f_1_zone_status','f_1_zone_buff_debuff_status','f_2_zone_status','f_2_zone_buff_debuff_status','f_3_zone_status','f_3_zone_buff_debuff_status','f_4_zone_status','f_4_zone_buff_debuff_status','f_5_zone_status','f_5_zone_buff_debuff_status','f_6_zone_status','f_6_zone_buff_debuff_status','red_1_bullet_left','red_2_bullet_left','blue_1_bullet_left','blue_2_bullet_left','stamp']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint16','uint16','uint16','uint16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       f_1_zone_status,f_1_zone_buff_debuff_status,f_2_zone_status,f_2_zone_buff_debuff_status,f_3_zone_status,f_3_zone_buff_debuff_status,f_4_zone_status,f_4_zone_buff_debuff_status,f_5_zone_status,f_5_zone_buff_debuff_status,f_6_zone_status,f_6_zone_buff_debuff_status,red_1_bullet_left,red_2_bullet_left,blue_1_bullet_left,blue_2_bullet_left,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IcraBuffDebuffZoneStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.f_1_zone_status is None:
        self.f_1_zone_status = 0
      if self.f_1_zone_buff_debuff_status is None:
        self.f_1_zone_buff_debuff_status = 0
      if self.f_2_zone_status is None:
        self.f_2_zone_status = 0
      if self.f_2_zone_buff_debuff_status is None:
        self.f_2_zone_buff_debuff_status = 0
      if self.f_3_zone_status is None:
        self.f_3_zone_status = 0
      if self.f_3_zone_buff_debuff_status is None:
        self.f_3_zone_buff_debuff_status = 0
      if self.f_4_zone_status is None:
        self.f_4_zone_status = 0
      if self.f_4_zone_buff_debuff_status is None:
        self.f_4_zone_buff_debuff_status = 0
      if self.f_5_zone_status is None:
        self.f_5_zone_status = 0
      if self.f_5_zone_buff_debuff_status is None:
        self.f_5_zone_buff_debuff_status = 0
      if self.f_6_zone_status is None:
        self.f_6_zone_status = 0
      if self.f_6_zone_buff_debuff_status is None:
        self.f_6_zone_buff_debuff_status = 0
      if self.red_1_bullet_left is None:
        self.red_1_bullet_left = 0
      if self.red_2_bullet_left is None:
        self.red_2_bullet_left = 0
      if self.blue_1_bullet_left is None:
        self.blue_1_bullet_left = 0
      if self.blue_2_bullet_left is None:
        self.blue_2_bullet_left = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.f_1_zone_status = 0
      self.f_1_zone_buff_debuff_status = 0
      self.f_2_zone_status = 0
      self.f_2_zone_buff_debuff_status = 0
      self.f_3_zone_status = 0
      self.f_3_zone_buff_debuff_status = 0
      self.f_4_zone_status = 0
      self.f_4_zone_buff_debuff_status = 0
      self.f_5_zone_status = 0
      self.f_5_zone_buff_debuff_status = 0
      self.f_6_zone_status = 0
      self.f_6_zone_buff_debuff_status = 0
      self.red_1_bullet_left = 0
      self.red_2_bullet_left = 0
      self.blue_1_bullet_left = 0
      self.blue_2_bullet_left = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12B4H2I().pack(_x.f_1_zone_status, _x.f_1_zone_buff_debuff_status, _x.f_2_zone_status, _x.f_2_zone_buff_debuff_status, _x.f_3_zone_status, _x.f_3_zone_buff_debuff_status, _x.f_4_zone_status, _x.f_4_zone_buff_debuff_status, _x.f_5_zone_status, _x.f_5_zone_buff_debuff_status, _x.f_6_zone_status, _x.f_6_zone_buff_debuff_status, _x.red_1_bullet_left, _x.red_2_bullet_left, _x.blue_1_bullet_left, _x.blue_2_bullet_left, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.f_1_zone_status, _x.f_1_zone_buff_debuff_status, _x.f_2_zone_status, _x.f_2_zone_buff_debuff_status, _x.f_3_zone_status, _x.f_3_zone_buff_debuff_status, _x.f_4_zone_status, _x.f_4_zone_buff_debuff_status, _x.f_5_zone_status, _x.f_5_zone_buff_debuff_status, _x.f_6_zone_status, _x.f_6_zone_buff_debuff_status, _x.red_1_bullet_left, _x.red_2_bullet_left, _x.blue_1_bullet_left, _x.blue_2_bullet_left, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_12B4H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12B4H2I().pack(_x.f_1_zone_status, _x.f_1_zone_buff_debuff_status, _x.f_2_zone_status, _x.f_2_zone_buff_debuff_status, _x.f_3_zone_status, _x.f_3_zone_buff_debuff_status, _x.f_4_zone_status, _x.f_4_zone_buff_debuff_status, _x.f_5_zone_status, _x.f_5_zone_buff_debuff_status, _x.f_6_zone_status, _x.f_6_zone_buff_debuff_status, _x.red_1_bullet_left, _x.red_2_bullet_left, _x.blue_1_bullet_left, _x.blue_2_bullet_left, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.f_1_zone_status, _x.f_1_zone_buff_debuff_status, _x.f_2_zone_status, _x.f_2_zone_buff_debuff_status, _x.f_3_zone_status, _x.f_3_zone_buff_debuff_status, _x.f_4_zone_status, _x.f_4_zone_buff_debuff_status, _x.f_5_zone_status, _x.f_5_zone_buff_debuff_status, _x.f_6_zone_status, _x.f_6_zone_buff_debuff_status, _x.red_1_bullet_left, _x.red_2_bullet_left, _x.blue_1_bullet_left, _x.blue_2_bullet_left, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_12B4H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12B4H2I = None
def _get_struct_12B4H2I():
    global _struct_12B4H2I
    if _struct_12B4H2I is None:
        _struct_12B4H2I = struct.Struct("<12B4H2I")
    return _struct_12B4H2I
