# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/ShootCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ShootCmd(genpy.Message):
  _md5sum = "b25a3c00a92bb8eead2eb72002d6d2f8"
  _type = "rm_msgs/ShootCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 STOP = 0
uint8 READY = 1
uint8 PUSH = 2

uint8 SPEED_ZERO_FOR_TEST = 0
uint8 SPEED_10M_PER_SECOND = 1
uint8 SPEED_15M_PER_SECOND = 2
uint8 SPEED_16M_PER_SECOND = 3
uint8 SPEED_18M_PER_SECOND = 4
uint8 SPEED_30M_PER_SECOND = 5

uint8 mode
uint8 speed
float64 hz
time stamp
"""
  # Pseudo-constants
  STOP = 0
  READY = 1
  PUSH = 2
  SPEED_ZERO_FOR_TEST = 0
  SPEED_10M_PER_SECOND = 1
  SPEED_15M_PER_SECOND = 2
  SPEED_16M_PER_SECOND = 3
  SPEED_18M_PER_SECOND = 4
  SPEED_30M_PER_SECOND = 5

  __slots__ = ['mode','speed','hz','stamp']
  _slot_types = ['uint8','uint8','float64','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode,speed,hz,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ShootCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mode is None:
        self.mode = 0
      if self.speed is None:
        self.speed = 0
      if self.hz is None:
        self.hz = 0.
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.mode = 0
      self.speed = 0
      self.hz = 0.
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd2I().pack(_x.mode, _x.speed, _x.hz, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.mode, _x.speed, _x.hz, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2Bd2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd2I().pack(_x.mode, _x.speed, _x.hz, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.mode, _x.speed, _x.hz, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2Bd2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bd2I = None
def _get_struct_2Bd2I():
    global _struct_2Bd2I
    if _struct_2Bd2I is None:
        _struct_2Bd2I = struct.Struct("<2Bd2I")
    return _struct_2Bd2I
