# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/SupplyProjectileAction.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class SupplyProjectileAction(genpy.Message):
  _md5sum = "e26c5d955511e834893fa4c75036d963"
  _type = "rm_msgs/SupplyProjectileAction"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 supply_projectile_id
uint8 supply_robot_id
uint8 supply_projectile_step
uint8 supply_projectile_num

time stamp
"""
  __slots__ = ['supply_projectile_id','supply_robot_id','supply_projectile_step','supply_projectile_num','stamp']
  _slot_types = ['uint8','uint8','uint8','uint8','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       supply_projectile_id,supply_robot_id,supply_projectile_step,supply_projectile_num,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SupplyProjectileAction, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.supply_projectile_id is None:
        self.supply_projectile_id = 0
      if self.supply_robot_id is None:
        self.supply_robot_id = 0
      if self.supply_projectile_step is None:
        self.supply_projectile_step = 0
      if self.supply_projectile_num is None:
        self.supply_projectile_num = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.supply_projectile_id = 0
      self.supply_robot_id = 0
      self.supply_projectile_step = 0
      self.supply_projectile_num = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B2I().pack(_x.supply_projectile_id, _x.supply_robot_id, _x.supply_projectile_step, _x.supply_projectile_num, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.supply_projectile_id, _x.supply_robot_id, _x.supply_projectile_step, _x.supply_projectile_num, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_4B2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B2I().pack(_x.supply_projectile_id, _x.supply_robot_id, _x.supply_projectile_step, _x.supply_projectile_num, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.supply_projectile_id, _x.supply_robot_id, _x.supply_projectile_step, _x.supply_projectile_num, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_4B2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B2I = None
def _get_struct_4B2I():
    global _struct_4B2I
    if _struct_4B2I is None:
        _struct_4B2I = struct.Struct("<4B2I")
    return _struct_4B2I
