(cl:in-package rm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          REAL_POS_X-VAL
          REAL_POS_X
          REAL_POS_Y-VAL
          REAL_POS_Y
          REAL_POS_Z-VAL
          REAL_POS_Z
          REAL_VEL_X-VAL
          REAL_VEL_X
          REAL_VEL_Y-VAL
          REAL_VEL_Y
          REAL_VEL_Z-VAL
          REAL_VEL_Z
          FILTERED_POS_X-VAL
          FILTERED_POS_X
          FILTERED_POS_Y-VAL
          FILTERED_POS_Y
          FILTERED_POS_Z-VAL
          FILTERED_POS_Z
          FILTERED_VEL_X-VAL
          FILTERED_VEL_X
          FILTERED_VEL_Y-VAL
          FILTERED_VEL_Y
          FILTERED_VEL_Z-VAL
          FILTERED_VEL_Z
          FILTERED_CENTER_X-VAL
          FILTERED_CENTER_X
          FILTERED_CENTER_Y-VAL
          FILTERED_CENTER_Y
          FILTERED_CENTER_Z-VAL
          FILTERED_CENTER_Z
          REAL_GYRO_VEL-VAL
          REAL_GYRO_VEL
          FILTERED_GYRO_VEL-VAL
          FILTERED_GYRO_VEL
))