(cl:in-package rm_msgs-msg)
(cl:export '(SUPPLY_PROJECTILE_ID-VAL
          SUPPLY_PROJECTILE_ID
          SUPPLY_ROBOT_ID-VAL
          SUPPLY_ROBOT_ID
          SUPPLY_PROJECTILE_STEP-VAL
          SUPPLY_PROJECTILE_STEP
          SUPPLY_PROJECTILE_NUM-VAL
          SUPPLY_PROJECTILE_NUM
          STAMP-VAL
          STAMP
))