(cl:in-package rm_msgs-msg)
(cl:export '(CH_L_X-VAL
          CH_L_X
          CH_L_Y-VAL
          CH_L_Y
          CH_R_X-VAL
          CH_R_X
          CH_R_Y-VAL
          CH_R_Y
          S_L-VAL
          S_L
          S_R-VAL
          S_R
          WHEEL-VAL
          WHEEL
          M_X-VAL
          M_X
          M_Y-VAL
          M_Y
          M_Z-VAL
          M_Z
          P_L-VAL
          P_L
          P_R-VAL
          P_R
          KEY_W-VAL
          KEY_W
          KEY_S-VAL
          KEY_S
          KEY_A-VAL
          KEY_A
          KEY_D-VAL
          KEY_D
          KEY_SHIFT-VAL
          KEY_SHIFT
          KEY_CTRL-VAL
          KEY_CTRL
          KEY_Q-VAL
          KEY_Q
          KEY_E-VAL
          KEY_E
          KEY_R-VAL
          KEY_R
          KEY_F-VAL
          KEY_F
          KEY_G-VAL
          KEY_G
          KEY_Z-VAL
          KEY_Z
          KEY_X-VAL
          KEY_X
          KEY_C-VAL
          KEY_C
          KEY_V-VAL
          KEY_V
          KEY_B-VAL
          KEY_B
          STAMP-VAL
          STAMP
))