(cl:in-package rm_msgs-msg)
(cl:export '(STAMP-VAL
          STAMP
          NAME-VAL
          NAME
          TYPE-VAL
          TYPE
          BUS-VAL
          BUS
          ID-VAL
          ID
          HALTED-VAL
          HALTED
          NEED_CALIBRATION-VAL
          NEED_CALIBRATION
          CALIBRATED-VAL
          CALIBRATED
          CALIBRATION_READING-VAL
          CALIBRATION_READING
          POSITION_RAW-VAL
          POSITION_RAW
          VELOCITY_RAW-VAL
          VELOCITY_RAW
          TEMPERATURE-VAL
          TEMPERATURE
          CIRCLE-VAL
          CIRCLE
          LAST_POSITION_RAW-VAL
          LAST_POSITION_RAW
          FREQUENCY-VAL
          FREQUENCY
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          EFFORT-VAL
          EFFORT
          COMMANDED_EFFORT-VAL
          COMMANDED_EFFORT
          EXECUTED_EFFORT-VAL
          EXECUTED_EFFORT
          OFFSET-VAL
          OFFSET
))