(cl:in-package rm_msgs-msg)
(cl:export '(DART_LAUNCH_OPENING_STATUS-VAL
          DART_LAUNCH_OPENING_STATUS
          DART_ATTACK_TARGET-VAL
          DART_ATTACK_TARGET
          TARGET_CHANGE_TIME-VAL
          TARGET_CHANGE_TIME
          FIRST_DART_SPEED-VAL
          FIRST_DART_SPEED
          SECOND_DART_SPEED-VAL
          SECOND_DART_SPEED
          THIRD_DART_SPEED-VAL
          THIRD_DART_SPEED
          FOURTH_DART_SPEED-VAL
          FOURTH_DART_SPEED
          LAST_DART_LAUNCH_TIME-VAL
          LAST_DART_LAUNCH_TIME
          OPERATE_LAUNCH_CMD_TIME-VAL
          OPERATE_LAUNCH_CMD_TIME
          STAMP-VAL
          STAMP
))