; Auto-generated. Do not edit!


(cl:in-package rm_msgs-msg)


;//! \htmlinclude EngineerResult.msg.html

(cl:defclass <EngineerResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass EngineerResult (<EngineerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <EngineerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'EngineerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rm_msgs-msg:<EngineerResult> is deprecated: use rm_msgs-msg:EngineerResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <EngineerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rm_msgs-msg:finish-val is deprecated.  Use rm_msgs-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <EngineerResult>) ostream)
  "Serializes a message object of type '<EngineerResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <EngineerResult>) istream)
  "Deserializes a message object of type '<EngineerResult>"
    (cl:setf (cl:slot-value msg 'finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<EngineerResult>)))
  "Returns string type for a message object of type '<EngineerResult>"
  "rm_msgs/EngineerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'EngineerResult)))
  "Returns string type for a message object of type 'EngineerResult"
  "rm_msgs/EngineerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<EngineerResult>)))
  "Returns md5sum for a message object of type '<EngineerResult>"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'EngineerResult)))
  "Returns md5sum for a message object of type 'EngineerResult"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<EngineerResult>)))
  "Returns full string definition for message of type '<EngineerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'EngineerResult)))
  "Returns full string definition for message of type 'EngineerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <EngineerResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <EngineerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'EngineerResult
    (cl:cons ':finish (finish msg))
))
