; Auto-generated. Do not edit!


(cl:in-package rm_msgs-msg)


;//! \htmlinclude EngineerFeedback.msg.html

(cl:defclass <EngineerFeedback> (roslisp-msg-protocol:ros-message)
  ((total_steps
    :reader total_steps
    :initarg :total_steps
    :type cl:fixnum
    :initform 0)
   (finished_step
    :reader finished_step
    :initarg :finished_step
    :type cl:fixnum
    :initform 0)
   (current_step
    :reader current_step
    :initarg :current_step
    :type cl:string
    :initform ""))
)

(cl:defclass EngineerFeedback (<EngineerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <EngineerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'EngineerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rm_msgs-msg:<EngineerFeedback> is deprecated: use rm_msgs-msg:EngineerFeedback instead.")))

(cl:ensure-generic-function 'total_steps-val :lambda-list '(m))
(cl:defmethod total_steps-val ((m <EngineerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rm_msgs-msg:total_steps-val is deprecated.  Use rm_msgs-msg:total_steps instead.")
  (total_steps m))

(cl:ensure-generic-function 'finished_step-val :lambda-list '(m))
(cl:defmethod finished_step-val ((m <EngineerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rm_msgs-msg:finished_step-val is deprecated.  Use rm_msgs-msg:finished_step instead.")
  (finished_step m))

(cl:ensure-generic-function 'current_step-val :lambda-list '(m))
(cl:defmethod current_step-val ((m <EngineerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rm_msgs-msg:current_step-val is deprecated.  Use rm_msgs-msg:current_step instead.")
  (current_step m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <EngineerFeedback>) ostream)
  "Serializes a message object of type '<EngineerFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_steps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'finished_step)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'current_step))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'current_step))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <EngineerFeedback>) istream)
  "Deserializes a message object of type '<EngineerFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_steps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'finished_step)) (cl:read-byte istream))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_step) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'current_step) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<EngineerFeedback>)))
  "Returns string type for a message object of type '<EngineerFeedback>"
  "rm_msgs/EngineerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'EngineerFeedback)))
  "Returns string type for a message object of type 'EngineerFeedback"
  "rm_msgs/EngineerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<EngineerFeedback>)))
  "Returns md5sum for a message object of type '<EngineerFeedback>"
  "87397c03e34e8b8835ff0de452ee02e3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'EngineerFeedback)))
  "Returns md5sum for a message object of type 'EngineerFeedback"
  "87397c03e34e8b8835ff0de452ee02e3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<EngineerFeedback>)))
  "Returns full string definition for message of type '<EngineerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%uint8 total_steps~%uint8 finished_step~%string current_step~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'EngineerFeedback)))
  "Returns full string definition for message of type 'EngineerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%uint8 total_steps~%uint8 finished_step~%string current_step~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <EngineerFeedback>))
  (cl:+ 0
     1
     1
     4 (cl:length (cl:slot-value msg 'current_step))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <EngineerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'EngineerFeedback
    (cl:cons ':total_steps (total_steps msg))
    (cl:cons ':finished_step (finished_step msg))
    (cl:cons ':current_step (current_step msg))
))
