; Auto-generated. Do not edit!


(cl:in-package rm_msgs-msg)


;//! \htmlinclude EngineerGoal.msg.html

(cl:defclass <EngineerGoal> (roslisp-msg-protocol:ros-message)
  ((step_queue_name
    :reader step_queue_name
    :initarg :step_queue_name
    :type cl:string
    :initform ""))
)

(cl:defclass EngineerGoal (<EngineerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <EngineerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'EngineerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rm_msgs-msg:<EngineerGoal> is deprecated: use rm_msgs-msg:EngineerGoal instead.")))

(cl:ensure-generic-function 'step_queue_name-val :lambda-list '(m))
(cl:defmethod step_queue_name-val ((m <EngineerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rm_msgs-msg:step_queue_name-val is deprecated.  Use rm_msgs-msg:step_queue_name instead.")
  (step_queue_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <EngineerGoal>) ostream)
  "Serializes a message object of type '<EngineerGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'step_queue_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'step_queue_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <EngineerGoal>) istream)
  "Deserializes a message object of type '<EngineerGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'step_queue_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'step_queue_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<EngineerGoal>)))
  "Returns string type for a message object of type '<EngineerGoal>"
  "rm_msgs/EngineerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'EngineerGoal)))
  "Returns string type for a message object of type 'EngineerGoal"
  "rm_msgs/EngineerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<EngineerGoal>)))
  "Returns md5sum for a message object of type '<EngineerGoal>"
  "e30ffeaaa0cfd516d274467b24b53a8a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'EngineerGoal)))
  "Returns md5sum for a message object of type 'EngineerGoal"
  "e30ffeaaa0cfd516d274467b24b53a8a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<EngineerGoal>)))
  "Returns full string definition for message of type '<EngineerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%string step_queue_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'EngineerGoal)))
  "Returns full string definition for message of type 'EngineerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%string step_queue_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <EngineerGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'step_queue_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <EngineerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'EngineerGoal
    (cl:cons ':step_queue_name (step_queue_name msg))
))
