// Auto-generated. Do not edit!

// (in-package rm_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class EngineerGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.step_queue_name = null;
    }
    else {
      if (initObj.hasOwnProperty('step_queue_name')) {
        this.step_queue_name = initObj.step_queue_name
      }
      else {
        this.step_queue_name = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type EngineerGoal
    // Serialize message field [step_queue_name]
    bufferOffset = _serializer.string(obj.step_queue_name, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type EngineerGoal
    let len;
    let data = new EngineerGoal(null);
    // Deserialize message field [step_queue_name]
    data.step_queue_name = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.step_queue_name);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rm_msgs/EngineerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e30ffeaaa0cfd516d274467b24b53a8a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    string step_queue_name
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new EngineerGoal(null);
    if (msg.step_queue_name !== undefined) {
      resolved.step_queue_name = msg.step_queue_name;
    }
    else {
      resolved.step_queue_name = ''
    }

    return resolved;
    }
};

module.exports = EngineerGoal;
